# -----------------------------------------------------------------------------
# SLG Comms Travis-CI build configuration file
# -----------------------------------------------------------------------------

language: php

# -----------------------------------------------------------------------------
# Environment setup and test scripts execution
#


# -----------------------------------------------------------------------------
# What to build, and on which platforms
#

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=mysql

matrix:
  allow_failures:
    - php: 7.2


# -----------------------------------------------------------------------------
# Notifications
#

notifications:
  email:
    on_success: change
    on_failure: always
