# -----------------------------------------------------------------------------
# SLG Comms Travis-CI build configuration file
# -----------------------------------------------------------------------------

language: php

# -----------------------------------------------------------------------------
# Environment setup and test scripts execution
#


# -----------------------------------------------------------------------------
# What to build, and on which platforms
#

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=mysql

matrix:
  include:
    # Add a specific build for Documentation
    - env: DOCBOOK=1
      # Using Ruby as it's preinstalled and we don't need PHP to build docs
      language: ruby
      addons:
        apt:
          packages:
            - publican

  allow_failures:
    - php: 7.2


# -----------------------------------------------------------------------------
# Notifications
#

notifications:
  email:
    on_success: change
    on_failure: always
